package com.battlesbudz.jarvis.v2.voice

/** Versioned fixed inputs: all profiles get identical text and simulated token delivery. */
object TtsBenchmarkSamples {
    val longNarration = """The lantern glowed beside the river. Mira followed a narrow path through the trees, carrying a map her grandfather had drawn. Across the water, an old clock tower stood above a village of blue rooftops. Its bell had been silent for many years. > At the bridge she met a gardener with a basket of apples. He pointed toward a little house beside the tower and told her that the keeper had left a letter there. Mira thanked him and crossed the bridge slowly. Beneath her feet, the river carried fallen leaves toward the sea. > Inside the house, a copper kettle rested on a cold stove. There were three cups on the table, a blue coat beside the door, and a folded letter underneath a stone. The letter described a silver key hidden in the garden. It also contained a curious sentence: the word stop had once been painted on the tower gate. Mira read the sentence quietly and continued searching. > A small brown dog appeared at the window. It watched her for a moment, then ran toward an apple tree. Beneath the tree was a wooden box. The key fitted the box perfectly, but inside there was only another map. This one showed the clock tower from above, with a narrow staircase drawn around its outer wall. > The keeper's final note quoted his old teacher: “Goodbye is sometimes the beginning of another journey.” Mira put the note in her pocket. She climbed the staircase with the dog waiting below. When she reached the top, the village looked peaceful in the evening light. She turned the handle beside the clock, and the bell rang once. Somewhere along the river, the gardener looked up and smiled."""
    val all = linkedMapOf(
        "short-opening-v2" to "I understand. I can keep up with what you are saying and process your requests. I am ready when you are.",
        "paragraph-v1" to "Good evening, sir. Your next appointment begins in twenty minutes. There is time for a cup of tea, provided we do not attempt to invent a new kettle first. I will keep the details ready while you finish what you are doing.",
        "story-v1" to "Kiko stood on the deck as the moon rose above the island. The little monkey had found a map inside an old brass compass, and tonight his crew would follow it. Beyond the reef, a blue light flickered beneath the waves. Kiko lowered a lantern and discovered the roof of a sunken library. Its windows were still glowing. He smiled, tied a rope around his waist, and handed the other end to his first mate. Gold could wait. Somewhere below them was a story that no pirate had ever heard, and Kiko intended to bring it home."
    )
}
